mqtt:
  enabled: true
  host: mosquitto
  port: 1883

detectors:
  cpu1:
    type: cpu

cameras:
  demo_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/live
          roles:
            - detect
            - record
    detect:
      enabled: false
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: all
