# Mosquitto MQTT Broker Configuration for VisionOS

persistence true
persistence_location /mosquitto/data/

# MQTT Default Port
listener 1883
allow_anonymous true

# WebSockets Port
listener 9001
protocol websockets
allow_anonymous true

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
